### ISSUE TITLE
Responsive design glitch in the heading area (between max-width 760px and 700px)

### ISSUE THREAD

**Issue by glowinginthedark** [hackathonistas/hackathonistas.github.io#11]
The font size needs to change at a smaller max-width.

Also, some media queries are at the top which may get overridden by regular properties defined after them. They need to be moved to the bottom.

![image](https://user-images.githubusercontent.com/33921776/56477411-01b53d80-645a-11e9-87af-81782fa82163.png)

**Comment by junaidrahim** [comment]
Resolved in https://github.com/hackathonistas/hackathonistas.github.io/pull/16
